version: '2.1'
services:
  api:
    build:
      context: .
    hostname: api
    ports:
      - 8000:8000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: "bridge"

  mysql:
    image: mysql:${MYSQL_VERSION}
    hostname: database
    expose:
      - 3306
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: "bridge"

volumes:
    db_data: {}