name: Deploy Nginx Configuration

on:
  push:
    branches:
      - master
    # paths:
    #   - 'nginx/**'

env:
  CONF_PATH: nginx
  NGINX_PATH: /etc/nginx

jobs:
  Build_And_Deploy:
    runs-on: stockholm
    steps:
      - uses: actions/checkout@v2
      - name: Update config files
        run: |
          sudo cp $CONF_PATH/nginx.conf $NGINX_PATH/
          sudo cp -R $CONF_PATH/conf.d/** $NGINX_PATH/conf.d/

      - name: Verify nginx conf
        run: sudo nginx -t
      
      - name: Restart nginx
        run: sudo systemctl restart nginx
