name: Deploy Frontend Application

on:
  push:
    branches:
      - master
    paths:
      - 'packages/@letsdoc/client/**'
      - 'package*'
      - yarn.lock
      - lerna.json
      - .github/workflows/deploy-frontend.yml

env:
  CLIENT_PATH: packages/@letsdoc/client 
  BUILD_PATH: packages/@letsdoc/client/dist
  STATIC_PATH: /var/www/html
  BACKEND_URL: https://api.letsdoc.serhiiromaniuk.com/api/v1/
  DOMAIN: letsdoc.serhiiromaniuk.com

jobs:
  Build_And_Deploy:
    runs-on: stockholm
    steps:
      - uses: actions/checkout@v2
      - name: Verify components
        run: |
          node --version
          npm --version

      - name: Bootstrap Packages
        run: npm run bootstrap

      - name: Build Frontend
        run: BACKEND_URL=${BACKEND_URL} npm run build:frontend

      - name: Move build files to nginx
        run: |
          sudo rm -rf $STATIC_PATH/**
          sudo cp -R $CLIENT_PATH/public/.well-known $BUILD_PATH/
          sudo cp -R $BUILD_PATH/** $STATIC_PATH/

      - name: Restart nginx
        run: sudo systemctl restart nginx
