name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  Build_And_Deploy:
    runs-on: stockholm
    steps:
      - uses: actions/checkout@v2
      - name: Verify node and install version
        run: node --version
